# Generated by Django 2.1.1 on 2019-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191211_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='answered',
            name='name',
            field=models.TextField(max_length=14),
        ),
        migrations.AlterField(
            model_name='answered',
            name='question',
            field=models.TextField(max_length=60),
        ),
    ]
