# Generated by Django 2.1.1 on 2019-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
