# Generated by Django 2.1.1 on 2019-12-10 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('height', models.IntegerField(blank=True, default=167, null=True)),
                ('weight', models.IntegerField(blank=True, default=65, null=True)),
                ('age', models.IntegerField(blank=True, default=25, null=True)),
                ('exc_lvl', models.CharField(blank=True, choices=[('0', 'Little to no exercise'), ('1', 'Light exercise (1?3 days per week)'), ('2', 'Moderate exercise (3?5 days per week)'), ('3', 'Heavy exercise (6?7 days per week)'), ('4', 'Very heavy exercise (twice per day, extra heavy workouts)')], default=0, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='enter a valid phone number', regex='^[1-9]\\d{9}$')])),
                ('profile_pic', models.ImageField(blank=True, default='prof1.jpg', null=True, upload_to='profile_pics')),
                ('my_trainers', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
