# Generated by Django 2.1.1 on 2019-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20191211_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='owned',
            name='ref_code',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='owned',
            name='user_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='user_name',
            field=models.TextField(max_length=100),
        ),
    ]
