# Generated by Django 2.1.1 on 2019-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_amount_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
